name: ðŸš€ Deploy Backend to K8s

on:
  push:
    branches: [ main ]
    paths:
      - 'portfolio-api/**'
      - '.github/workflows/backend.yml'

jobs:
  build-push-and-rollout:
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ“¥ Checkout
        uses: actions/checkout@v4

      - name: ðŸ” Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME_BACK }}
          password: ${{ secrets.DOCKERHUB_TOKEN_BACK }}

      - name: ðŸ·ï¸ Build & Push (sha + latest)
        uses: docker/build-push-action@v6
        with:
          context: ./portfolio-api
          push: true
          tags: |
            kolie549/portfolio-api:${{ github.sha }}
            kolie549/portfolio-api:latest

      - name: ðŸ§° Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      - name: ðŸŒ Configure kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config

      - name: ðŸ”„ Set image & rollout
        run: |
          kubectl set image deployment/portfolio-api \
            portfolio-api=kolie549/portfolio-api:${{ github.sha }} -n portfolio --record
          kubectl rollout status deployment/portfolio-api -n portfolio --timeout=120s
