name: ðŸš€ Deploy Backend to K8s

on:
  push:
    branches: [ main ]
    paths:
      - 'portfolio-api/**'
      - '.github/workflows/backend.yml'

jobs:
  build-push-and-rollout:
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ“¥ Checkout
        uses: actions/checkout@v4

      - name: ðŸ” Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME_BACK }}
          password: ${{ secrets.DOCKERHUB_TOKEN_BACK }}

      - name: ðŸ·ï¸ Build & Push (sha + latest)
        uses: docker/build-push-action@v6
        with:
          context: ./portfolio-api
          push: true
          tags: |
            kolie549/portfolio-api:${{ github.sha }}
            kolie549/portfolio-api:latest

      - name: ðŸšª SSH on EC2 & rollout BACK
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "[INFO] Hostname: $(hostname)"
            echo "[INFO] kubectl: $(which kubectl)"
            echo "[ROLLING] set image portfolio-api -> kolie549/portfolio-api:${{ github.sha }}"
            kubectl -n portfolio set image deployment/portfolio-api \
              portfolio-api=kolie549/portfolio-api:${{ github.sha }} --record
            echo "[WAIT] rollout status..."
            kubectl -n portfolio rollout status deployment/portfolio-api --timeout=180s
            echo "[DONE] rollout ok"
