name: ğŸš€ Deploy Backend to Docker Hub

on:
  push:
    branches:
      - main
    paths:
      - 'portfolio-api/**'
      - '.github/workflows/backend.yml'

jobs:
  build-and-push-backend:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Checkout code
        uses: actions/checkout@v3

      - name: ğŸ” Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME_BACK }}
          password: ${{ secrets.DOCKERHUB_TOKEN_BACK }}

      - name: ğŸ› ï¸ Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./portfolio-api
          push: true
          tags: kolie549/portfolio-api:latest

      - name: ğŸ”” Notify FastAPI to deploy
        run: |
          curl -X POST http://kolie-portfolio.org:8000/webhook \
            -H "X-Hub-Signature-256: sha256=$(echo -n 'dummy' | openssl dgst -sha256 -hmac 'kolie-super-devops-2025' | sed 's/^.* //')" \
            -H "Content-Type: application/json" \
            -d '{"event":"deploy"}'
