name: ðŸš€ Deploy Frontend to K8s

on:
  push:
    branches: [ main ]
    paths:
      - 'portfolio-template/**'
      - '.github/workflows/frontend.yml'

jobs:
  build-push-and-rollout:
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ“¥ Checkout
        uses: actions/checkout@v4

      - name: ðŸ” Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME_FRONT }}
          password: ${{ secrets.DOCKERHUB_TOKEN_FRONT }}

      - name: ðŸ·ï¸ Build & Push (sha + latest)
        uses: docker/build-push-action@v6
        with:
          context: ./portfolio-template
          push: true
          tags: |
            kolierene975/portfolio-front:${{ github.sha }}
            kolierene975/portfolio-front:latest

      - name: ðŸ§° Install kubectl
        uses: azure/setup-kubectl@v4

      - name: ðŸŒ Configure kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config

      - name: ðŸ”„ Set image & rollout
        run: |
          kubectl set image deployment/portfolio-front \
            portfolio-front=kolierene975/portfolio-front:${{ github.sha }} -n portfolio --record
          kubectl rollout status deployment/portfolio-front -n portfolio --timeout=120s
