name: ğŸš€ Deploy Frontend to Docker Hub

on:
  push:
    branches:
      - main
    paths:
      - 'portfolio-template/**'
      - '.github/workflows/frontend.yml'

jobs:
  build-and-push-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Checkout code
        uses: actions/checkout@v3

      - name: ğŸ” Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME_FRONT }}
          password: ${{ secrets.DOCKERHUB_TOKEN_FRONT }}

      - name: ğŸ› ï¸ Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./portfolio-template
          push: true
          tags: kolierene975/portfolio-front:latest
